FROM node:19-slim
WORKDIR /app

## install tini
ADD https://github.com/krallin/tini/releases/download/v0.19.0/tini /bin/tini
RUN chmod +x /bin/tini

## install all node.js dependencies
COPY package.json package-lock.json ./
RUN npm ci

COPY ./prisma ./prisma

ENTRYPOINT ["tini", "--"]
CMD ["./node_modules/.bin/prisma", "migrate", "deploy"]
