scalar DateTime

type Query {
  video(id: ID!): Video!
  videos(input: GetVideosInput): VideoCollection!

  tag(id: ID!): Tag!
  tags(input: GetTagsInput): TagCollection!

  mylist(id: ID!): Mylist!

  searchVideos(query: String!, limit: Int! = 10, skip: Int! = 0): SearchVideosResult!
  searchTags(query: String!, limit: Int! = 10, skip: Int! = 0): SearchTagsResult!

  user(name: String!): User!
  whoami: User!

  niconicoSource(id: ID!): NiconicoSource!
  findNiconicoSource(id: ID!): NiconicoSource
}

type Mutation {
  registerTag(input: RegisterTagInput!): RegisterTagPayload!
  registerVideo(input: RegisterVideoInput!): RegisterVideoPayload!

  tagVideo(input: TagVideoInput!): VideoAddTagHistoryItem!
  untagVideo(input: UntagVideoInput!): VideoDeleteTagHistoryItem!

  createMylist(input: CreateMylistInput!): CreateMylistPayload!

  likeVideo(input: LikeVideoInput!): LikeVideoPayload!
  undoLikeVideo(input: UndoLikeVideoInput!): UndoLikeVideoPayload!

  addVideoToMylist(input: AddVideoToMylistInput!): AddVideoToMylistPayload!
  removeVideoFromMylist(input: RemoveVideoFromMylistInput!): RemoveVideoFromMylistPayload!
}

type Video {
  id: ID!
  title: String!
  titles: [VideoTitle!]!
  thumbnailUrl: String!
  thumbnails: [VideoThumbnail!]!
  tags: [Tag!]!
  hasTag(id: ID!): Boolean!
  history(skip: Int! = 0, limit: Int! = 10, order: VideoHistoryOrder! = { createdAt: DESC }): [VideoHistoryItem!]!
  registeredAt: DateTime!
  similarVideos(input: VideoSimilarVideosInput): VideoSimilarVideosPayload!
}

input VideoHistoryOrder {
  createdAt: SortOrder
}

enum SortOrder {
  ASC
  DESC
}

type VideoTitle {
  title: String!
  primary: Boolean!
}

type VideoThumbnail {
  imageUrl: String!
  primary: Boolean!
}

interface VideoSource {
  videoId: String!
  url: String!
}

type NiconicoVideoSource implements VideoSource {
  videoId: String!
  url: String!
}

type YoutubeVideoSource implements VideoSource {
  videoId: String!
  url: String!
}

interface VideoHistoryItem {
  id: ID!
  user: User!
  createdAt: DateTime!
  video: Video!
}

type VideoRegisterHistoryItem implements VideoHistoryItem {
  id: ID!
  user: User!
  createdAt: DateTime!
  video: Video!
}

type VideoAddTitleHistoryItem implements VideoHistoryItem {
  id: ID!
  user: User!
  createdAt: DateTime!
  video: Video!
  title: String!
}

type VideoDeleteTitleHistoryItem implements VideoHistoryItem {
  id: ID!
  user: User!
  createdAt: DateTime!
  video: Video!
  title: String!
}

type VideoChangePrimaryTitleHistoryItem implements VideoHistoryItem {
  id: ID!
  user: User!
  createdAt: DateTime!
  video: Video!
  from: String
  to: String!
}

type VideoAddThumbnailHistoryItem implements VideoHistoryItem {
  id: ID!
  user: User!
  createdAt: DateTime!
  video: Video!
  thumbnail: String!
}

type VideoDeleteThumbnailHistoryItem implements VideoHistoryItem {
  id: ID!
  user: User!
  createdAt: DateTime!
  video: Video!
  thumbnail: String!
}

type VideoChangePrimaryThumbnailHistoryItem implements VideoHistoryItem {
  id: ID!
  user: User!
  createdAt: DateTime!
  video: Video!
  from: String
  to: String!
}

type VideoAddTagHistoryItem implements VideoHistoryItem {
  id: ID!
  user: User!
  createdAt: DateTime!
  video: Video!
  tag: Tag!
}

type VideoDeleteTagHistoryItem implements VideoHistoryItem {
  id: ID!
  user: User!
  createdAt: DateTime!
  video: Video!
  tag: Tag!
}

type VideoAddNiconicoSourceHistoryItem implements VideoHistoryItem {
  id: ID!
  user: User!
  createdAt: DateTime!
  video: Video!
  niconico: NiconicoSource!
}

input GetVideosInput {
  limit: Int = 10
  skip: Int = 0
  order: GetVideosInputOrder = { createdAt: DESC }
}

input GetVideosInputOrder {
  updatedAt: SortOrder
  createdAt: SortOrder
}

type VideoCollection {
  nodes: [Video!]!
}

input VideoSimilarVideosInput {
  limit: Int = 10
}

type VideoSimilarVideosPayload {
  items: [VideoSimilarVideoItem!]!
}

type VideoSimilarVideoItem {
  video: Video!
  score: Float!
}

type Tag {
  id: ID!
  type: TagType! @deprecated
  name: String!
  names: [TagName!]!

  taggedVideos: [Video!]!
  history: [TagHistoryItem!]!

  explicitParent: Tag
  parents: [TagParent!]!
  meaningless: Boolean!
}

type TagCollection {
  nodes: [Tag!]!
}

input GetTagsInput {
  limit: Int
  skip: Int
  order: GetTagsInputOrder = { updatedAt: DESC }
}

input GetTagsInputOrder {
  updatedAt: SortOrder
  createdAt: SortOrder
}

type TagName {
  name: String!
  primary: Boolean!
}

type TagParent {
  tag: Tag!
  explicit: Boolean!
}

enum TagType {
  COPYRIGHT
  MATERIAL
  MUSIC
  SERIES
  IMAGE
  TACTICS
  CLASS
  EVENT
}

interface TagHistoryItem {
  id: ID!
  user: User!
  createdAt: DateTime!
}

type TagRegisterHistoryItem implements TagHistoryItem {
  id: ID!
  user: User!
  createdAt: DateTime!
  tag: Tag!
}

type TagAddNameHistoryItem implements TagHistoryItem {
  id: ID!
  user: User!
  createdAt: DateTime!
  tag: Tag!
  name: String!
}

type TagDeleteNameHistoryItem implements TagHistoryItem {
  id: ID!
  user: User!
  createdAt: DateTime!
  tag: Tag!
  name: String!
}

type TagChangePrimaryNameHistoryItem implements TagHistoryItem {
  id: ID!
  user: User!
  createdAt: DateTime!
  tag: Tag!
  from: String
  to: String!
}

type SearchVideosResult {
  # count: Int!
  result: [SearchVideosResultItem!]!
}

type SearchVideosResultItem {
  matchedTitle: String!
  video: Video!
}

type SearchTagsResult {
  # count: Int!
  result: [SearchTagsResultItem!]!
}

type SearchTagsResultItem {
  matchedName: String!
  tag: Tag!
}

type User {
  id: ID!
  name: String!
  displayName: String!
  icon: String!

  favorites: Mylist!
  mylists(input: UserMylistsInput!): UserMylistsConnection!
}

input UserMylistsInput {
  limit: Int
  skip: Int
  order: UserMylistsInputOrder = { createdAt: ASC }
  range: [MylistShareRange!] = [PUBLIC]
}

input UserMylistsInputOrder {
  createdAt: SortOrder
  updatedAt: SortOrder
}

type UserMylistsConnection {
  nodes: [Mylist!]!
}

input RegisterTagInput {
  primaryName: String!
  extraNames: [String!]

  explicitParent: ID
  implicitParents: [ID!]
}

type RegisterTagPayload {
  tag: Tag!
}

input RegisterVideoInput {
  primaryTitle: String!
  extraTitles: [String!]
  tags: [ID!]!
  primaryThumbnail: String!
  sources: [RegisterVideoInputSource!]!
}

enum RegisterVideoInputSourceType {
  NICOVIDEO
  # YOUTUBE
}

input RegisterVideoInputSource {
  type: RegisterVideoInputSourceType!
  sourceId: String!
}

type RegisterVideoPayload {
  video: Video!
}

input TagVideoInput {
  videoId: ID!
  tagId: ID!
}

input UntagVideoInput {
  videoId: ID!
  tagId: ID!
}

type NiconicoSource {
  id: ID!
  video: Video
}

type Mylist {
  id: ID!
  title: String!
  holder: User!
  range: MylistShareRange!
  createdAt: DateTime!
  updatedAt: DateTime!

  registrations(input: MylistRegistrationsInput!): MylistRegistrationCollection!

  """
  マイリストの中にビデオが追加されているか．
  """
  includes(videoId: ID!): Boolean!
}

enum MylistShareRange {
  PUBLIC
  KNOW_LINK
  PRIVATE
}

type MylistRegistration {
  id: ID!
  video: Video!
  mylist: Mylist!

  createdAt: DateTime!
  updatedAt: DateTime!
  note: String
}

type MylistRegistrationCollection {
  nodes: [MylistRegistration!]!
}

input MylistRegistrationsInput {
  limit: Int
  skip: Int
  order: MylistRegistrationsInputOrder = { registeredAt: ASC }
}

input MylistRegistrationsInputOrder {
  createdAt: SortOrder
  updatedAt: SortOrder
}

input CreateMylistInput {
  title: String!
  range: MylistShareRange!
}

type CreateMylistPayload {
  mylist: Mylist!
}

input LikeVideoInput {
  videoId: ID!
}

type LikeVideoPayload {
  registration: MylistRegistration!
}

input UndoLikeVideoInput {
  videoId: ID!
}

type UndoLikeVideoPayload {
  video: Video!
  mylist: Mylist!
}

input AddVideoToMylistInput {
  videoId: ID!
  mylistId: ID!
  note: String
}

type AddVideoToMylistPayload {
  registration: MylistRegistration!
}

input RemoveVideoFromMylistInput {
  videoId: ID!
  mylistId: ID!
}

type RemoveVideoFromMylistPayload {
  video: Video!
  mylist: Mylist!
}
