-- CreateEnum
CREATE TYPE "VideoEventType" AS ENUM ('REGISTER', 'ADD_TITLE', 'REMOVE_TITLE', 'SET_PRIMARY_TITLE', 'CHANGE_PRIMARY_TITLE', 'ADD_THUMBNAIL', 'REMOVE_THUMBNAIL', 'SET_PRIMARY_THUMBNAIL', 'CHANGE_PRIMARY_THUMBNAIL', 'ADD_TAG', 'REMOVE_TAG', 'ADD_SEMITAG', 'ADD_NICOVIDEO_SOURCE', 'DELETE_NICOVIDEO_SOURCE', 'ADD_MYLIST', 'DELETE_MYLIST');

-- CreateTable
CREATE TABLE "VideoEvent" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "videoId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" "VideoEventType" NOT NULL,
    "payload" JSONB NOT NULL,

    CONSTRAINT "VideoEvent_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "VideoEvent" ADD CONSTRAINT "VideoEvent_videoId_fkey" FOREIGN KEY ("videoId") REFERENCES "Video"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VideoEvent" ADD CONSTRAINT "VideoEvent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
