-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "citext";

-- CreateEnum
CREATE TYPE "mylists_range_enum" AS ENUM ('PUBLIC', 'KNOW_LINK', 'PRIVATE');

-- CreateEnum
CREATE TYPE "users_role_enum" AS ENUM ('NORMAL', 'EDITOR', 'ADMINISTRATOR');

-- CreateTable
CREATE TABLE "migrations" (
    "id" SERIAL NOT NULL,
    "timestamp" BIGINT NOT NULL,
    "name" VARCHAR NOT NULL,

    CONSTRAINT "PK_8c82d7f526340ab734260ea46be" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mylist_group_mylist_inclusions" (
    "id" VARCHAR(26) NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "groupId" VARCHAR(26) NOT NULL,
    "mylistId" VARCHAR(26) NOT NULL,

    CONSTRAINT "PK_e0d0b6a037fdb9633296d165914" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mylist_groups" (
    "id" VARCHAR(26) NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "title" TEXT NOT NULL,
    "holderId" VARCHAR(26) NOT NULL,

    CONSTRAINT "PK_283e995beb055f327e92afeb787" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mylist_registrations" (
    "id" VARCHAR(26) NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "note" TEXT,
    "videoId" VARCHAR(26),
    "mylistId" VARCHAR(26),

    CONSTRAINT "PK_7f7232b504749e2c3d916353e89" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mylists" (
    "id" VARCHAR(26) NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "title" TEXT NOT NULL,
    "range" "mylists_range_enum" NOT NULL,
    "isLikeList" BOOLEAN NOT NULL,
    "holderId" VARCHAR(26) NOT NULL,

    CONSTRAINT "PK_2d3fcd4c9328d290bd0268dc1c8" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "nicovideo_video_sources" (
    "id" VARCHAR(26) NOT NULL,
    "sourceId" CITEXT NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "videoId" VARCHAR(26) NOT NULL,

    CONSTRAINT "PK_7acd648a4ecaada5bbeec79fe5c" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "semitags" (
    "id" VARCHAR(26) NOT NULL,
    "name" TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "resolved" BOOLEAN NOT NULL DEFAULT false,
    "videoId" VARCHAR(26),
    "tagId" VARCHAR(26),

    CONSTRAINT "PK_27c9b8f9e08f86a3576c300b2e1" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sessions" (
    "id" VARCHAR(26) NOT NULL,
    "secret" VARCHAR(64) NOT NULL,
    "expiredAt" TIMESTAMPTZ(6) NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "userId" VARCHAR(26) NOT NULL,

    CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tag_names" (
    "id" VARCHAR(26) NOT NULL,
    "name" TEXT NOT NULL,
    "primary" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "tagId" VARCHAR(26),

    CONSTRAINT "PK_844280ab35721a1e89497db5617" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tag_parents" (
    "id" VARCHAR(26) NOT NULL,
    "explicit" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "parentId" VARCHAR(26),
    "childId" VARCHAR(26),

    CONSTRAINT "PK_cc4322310226e2a49d6edc80d71" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tags" (
    "id" VARCHAR(26) NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "meaningless" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "PK_e7dc17249a1148a1970748eda99" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "users" (
    "id" VARCHAR(26) NOT NULL,
    "name" CITEXT NOT NULL,
    "displayName" TEXT NOT NULL,
    "icon" TEXT,
    "email" TEXT NOT NULL,
    "emailConfirmed" BOOLEAN NOT NULL DEFAULT false,
    "password" TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "role" "users_role_enum" NOT NULL DEFAULT 'NORMAL',

    CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "video_sources" (
    "id" VARCHAR(26) NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "source" TEXT NOT NULL,
    "sourceVideoId" TEXT NOT NULL,
    "videoId" VARCHAR(26) NOT NULL,

    CONSTRAINT "PK_2b4ff25794018ffbe9afdd25e95" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "video_tags" (
    "id" VARCHAR(26) NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "tagId" VARCHAR(26) NOT NULL,
    "videoId" VARCHAR(26) NOT NULL,

    CONSTRAINT "PK_46a3780fea7f7e85204356a3b4b" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "video_thumbnails" (
    "id" VARCHAR(26) NOT NULL,
    "imageUrl" TEXT NOT NULL,
    "primary" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "videoId" VARCHAR(26) NOT NULL,

    CONSTRAINT "PK_9540a7e1a10bcaad41085ca7dca" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "video_titles" (
    "id" VARCHAR(26) NOT NULL,
    "title" TEXT NOT NULL,
    "isPrimary" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "videoId" VARCHAR(26) NOT NULL,

    CONSTRAINT "PK_1eb43f207970e996784be5ff478" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "videos" (
    "id" VARCHAR(26) NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PK_e4c86c0cf95aff16e9fb8220f6b" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "UQ_208e64d42387623cad7f2e4fb6b" ON "nicovideo_video_sources"("sourceId");

-- CreateIndex
CREATE UNIQUE INDEX "UQ_76e7668f8eb32271df39070d2ca" ON "nicovideo_video_sources"("videoId");

-- CreateIndex
CREATE UNIQUE INDEX "UQ_51b8b26ac168fbe7d6f5653e6cf" ON "users"("name");

-- CreateIndex
CREATE UNIQUE INDEX "UQ_7995bc8220363477e15fff8bcdc" ON "video_tags"("tagId", "videoId");

-- AddForeignKey
ALTER TABLE "mylist_group_mylist_inclusions" ADD CONSTRAINT "FK_105128216044972f3ad4b507d03" FOREIGN KEY ("mylistId") REFERENCES "mylists"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "mylist_group_mylist_inclusions" ADD CONSTRAINT "FK_9e69a6b42c71dfae6fb726a73ac" FOREIGN KEY ("groupId") REFERENCES "mylist_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "mylist_groups" ADD CONSTRAINT "FK_715f1efaef409a44ec479f0e84f" FOREIGN KEY ("holderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "mylist_registrations" ADD CONSTRAINT "FK_30b4c5755140583330020e4639e" FOREIGN KEY ("videoId") REFERENCES "videos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "mylist_registrations" ADD CONSTRAINT "FK_abda40557147e25d8cb95fee078" FOREIGN KEY ("mylistId") REFERENCES "mylists"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "mylists" ADD CONSTRAINT "FK_a6e470bf3e6bbfb270f9295cb2e" FOREIGN KEY ("holderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "nicovideo_video_sources" ADD CONSTRAINT "FK_2d2697091069023ae1fffac0ea8" FOREIGN KEY ("videoId") REFERENCES "videos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "semitags" ADD CONSTRAINT "FK_037d6465fa7dd9a195533416f63" FOREIGN KEY ("videoId") REFERENCES "videos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "semitags" ADD CONSTRAINT "FK_3e324d47c1a1d957e2e6f2d9afc" FOREIGN KEY ("tagId") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "sessions" ADD CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "tag_names" ADD CONSTRAINT "FK_551baf525c6a275793afce4125e" FOREIGN KEY ("tagId") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "tag_parents" ADD CONSTRAINT "FK_ce25fe074ec6e65ce7e8f078a00" FOREIGN KEY ("childId") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "tag_parents" ADD CONSTRAINT "FK_f22a29123c357c414694215e018" FOREIGN KEY ("parentId") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "video_sources" ADD CONSTRAINT "FK_bbae903425b10f56551dc60148c" FOREIGN KEY ("videoId") REFERENCES "videos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "video_tags" ADD CONSTRAINT "FK_6f9964c104164fb5eed88b52f4a" FOREIGN KEY ("tagId") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "video_tags" ADD CONSTRAINT "FK_92a248c1d263a8eddb8ef92d750" FOREIGN KEY ("videoId") REFERENCES "videos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "video_thumbnails" ADD CONSTRAINT "FK_91f45ae79e0bf6f2dea2696112d" FOREIGN KEY ("videoId") REFERENCES "videos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "video_titles" ADD CONSTRAINT "FK_d69ac721691fba16dc5f08f0658" FOREIGN KEY ("videoId") REFERENCES "videos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
